package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "APPLICATION_COMPANY".
 */
public class ApplicationCompany implements java.io.Serializable {

    /** Not-null value. */
    private String CompanyID;
    /** Not-null value. */
    private String IndustryID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ApplicationCompany() {
    }

    public ApplicationCompany(String CompanyID, String IndustryID) {
        this.CompanyID = CompanyID;
        this.IndustryID = IndustryID;
    }

    /** Not-null value. */
    public String getCompanyID() {
        return CompanyID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    /** Not-null value. */
    public String getIndustryID() {
        return IndustryID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIndustryID(String IndustryID) {
        this.IndustryID = IndustryID;
    }

    // KEEP METHODS - put your custom methods here
    public void parserID(String[] inputStream){
		this.CompanyID=inputStream[0];
		this.IndustryID=inputStream[1];
	}
    // KEEP METHODS END

}
