package com.adsale.ChinaPlas.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.adsale.ChinaPlas.dao.CompanyCatalogProduct;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPANY_CATALOG_PRODUCT".
*/
public class CompanyCatalogProductDao extends AbstractDao<CompanyCatalogProduct, Void> {

    public static final String TABLENAME = "COMPANY_CATALOG_PRODUCT";

    /**
     * Properties of entity CompanyCatalogProduct.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CompanyID = new Property(0, Integer.class, "CompanyID", false, "COMPANY_ID");
        public final static Property CatalogProductSubID = new Property(1, String.class, "CatalogProductSubID", false, "CATALOG_PRODUCT_SUB_ID");
    };


    public CompanyCatalogProductDao(DaoConfig config) {
        super(config);
    }
    
    public CompanyCatalogProductDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPANY_CATALOG_PRODUCT\" (" + //
                "\"COMPANY_ID\" INTEGER," + // 0: CompanyID
                "\"CATALOG_PRODUCT_SUB_ID\" TEXT);"); // 1: CatalogProductSubID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPANY_CATALOG_PRODUCT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CompanyCatalogProduct entity) {
        stmt.clearBindings();
 
        Integer CompanyID = entity.getCompanyID();
        if (CompanyID != null) {
            stmt.bindLong(1, CompanyID);
        }
 
        String CatalogProductSubID = entity.getCatalogProductSubID();
        if (CatalogProductSubID != null) {
            stmt.bindString(2, CatalogProductSubID);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public CompanyCatalogProduct readEntity(Cursor cursor, int offset) {
        CompanyCatalogProduct entity = new CompanyCatalogProduct( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // CompanyID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // CatalogProductSubID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CompanyCatalogProduct entity, int offset) {
        entity.setCompanyID(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setCatalogProductSubID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(CompanyCatalogProduct entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(CompanyCatalogProduct entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
