package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "COMPANY_CATALOG_PRODUCT".
 */
public class CompanyCatalogProduct {

    private Integer CompanyID;
    private String CatalogProductSubID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CompanyCatalogProduct() {
    }

    public CompanyCatalogProduct(Integer CompanyID, String CatalogProductSubID) {
        this.CompanyID = CompanyID;
        this.CatalogProductSubID = CatalogProductSubID;
    }

    public Integer getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(Integer CompanyID) {
        this.CompanyID = CompanyID;
    }

    public String getCatalogProductSubID() {
        return CatalogProductSubID;
    }

    public void setCatalogProductSubID(String CatalogProductSubID) {
        this.CatalogProductSubID = CatalogProductSubID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
