package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.databinding.ObservableBoolean;
import android.os.Parcel;
import android.os.Parcelable;

import com.adsale.ChinaPlas.utils.AppUtil;
import com.adsale.ChinaPlas.utils.Constant;

/**
 * Entity mapped to table "COUNTRY".
 */
public class Country implements Parcelable {

    private String CountryID;
    private String CountryEng;
    private String CountryTC;
    private String CountrySC;
    private String SortTC;
    private String SortSC;
    private String SortEN;
    private String createdAt;
    private String updatedAt;


    // KEEP FIELDS - put your custom fields here
    public final ObservableBoolean isTypeLabel = new ObservableBoolean();
    public final ObservableBoolean selected = new ObservableBoolean(false);
    // KEEP FIELDS END
    private boolean IsDelete;
    public Country() {
    }

    public Country(String CountryID) {
        this.CountryID = CountryID;
    }

    public Country(String CountryID, String CountryEng, String CountryTC, String CountrySC, String SortTC, String SortSC, String SortEN, String createdAt, String updatedAt) {
        this.CountryID = CountryID;
        this.CountryEng = CountryEng;
        this.CountryTC = CountryTC;
        this.CountrySC = CountrySC;
        this.SortTC = SortTC;
        this.SortSC = SortSC;
        this.SortEN = SortEN;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public boolean isDelete() {
        return IsDelete;
    }

    public void setDelete(boolean delete) {
        IsDelete = delete;
    }

    public String getCountryID() {
        return CountryID;
    }

    public void setCountryID(String CountryID) {
        this.CountryID = CountryID;
    }

    public String getCountryEng() {
        return CountryEng;
    }

    public void setCountryEng(String CountryEng) {
        this.CountryEng = CountryEng;
    }

    public String getCountryTC() {
        return CountryTC;
    }

    public void setCountryTC(String CountryTC) {
        this.CountryTC = CountryTC;
    }

    public String getCountrySC() {
        return CountrySC;
    }

    public void setCountrySC(String CountrySC) {
        this.CountrySC = CountrySC;
    }

    public String getSortTC() {
        return SortTC;
    }

    public void setSortTC(String SortTC) {
        this.SortTC = SortTC;
    }

    public String getSortSC() {
        return SortSC;
    }

    public void setSortSC(String SortSC) {
        this.SortSC = SortSC;
    }

    public String getSortEN() {
        return SortEN;
    }

    public void setSortEN(String SortEN) {
        this.SortEN = SortEN;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    // KEEP METHODS - put your custom methods here
    public String getSort() {
        return AppUtil.getName(SortTC + Constant.TRAD_STROKE, SortEN, SortSC);
    }

    public String getCountryName() {
        return AppUtil.getName(CountryTC, CountryEng, CountrySC);
    }


    public void parser(String[] strings) {
        this.CountryID = strings[0];
        this.CountryEng = strings[1];
        this.CountryTC = strings[2];
        this.CountrySC = strings[3];
        this.SortTC = strings[4];
        this.SortSC = strings[5];
        this.SortEN = strings[6];
    }


    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.CountryID);
        dest.writeString(this.CountryEng);
        dest.writeString(this.CountryTC);
        dest.writeString(this.CountrySC);
        dest.writeString(this.SortTC);
        dest.writeString(this.SortSC);
        dest.writeString(this.SortEN);
        dest.writeString(this.createdAt);
        dest.writeString(this.updatedAt);
    }

    protected Country(Parcel in) {
        this.CountryID = in.readString();
        this.CountryEng = in.readString();
        this.CountryTC = in.readString();
        this.CountrySC = in.readString();
        this.SortTC = in.readString();
        this.SortSC = in.readString();
        this.SortEN = in.readString();
        this.createdAt = in.readString();
        this.updatedAt = in.readString();
    }

    public static final Parcelable.Creator<Country> CREATOR = new Parcelable.Creator<Country>() {
        public Country createFromParcel(Parcel source) {
            return new Country(source);
        }

        public Country[] newArray(int size) {
            return new Country[size];
        }
    };
}
