package com.adsale.ChinaPlas.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.adsale.ChinaPlas.dao.MainIcon;
import com.adsale.ChinaPlas.dao.ApplicationIndustry;
import com.adsale.ChinaPlas.dao.ApplicationCompany;
import com.adsale.ChinaPlas.dao.Country;
import com.adsale.ChinaPlas.dao.Exhibitor;
import com.adsale.ChinaPlas.dao.ExhibitorUserUpdate;
import com.adsale.ChinaPlas.dao.Floor;
import com.adsale.ChinaPlas.dao.MapFloor;
import com.adsale.ChinaPlas.dao.NameCard;
import com.adsale.ChinaPlas.dao.News;
import com.adsale.ChinaPlas.dao.NewsLink;
import com.adsale.ChinaPlas.dao.ProductID;
import com.adsale.ChinaPlas.dao.ScheduleInfo;
import com.adsale.ChinaPlas.dao.UpdateDate;
import com.adsale.ChinaPlas.dao.WebContent;
import com.adsale.ChinaPlas.dao.BussinessMapping;
import com.adsale.ChinaPlas.dao.HistoryExhibitor;
import com.adsale.ChinaPlas.dao.UpdateCenter;
import com.adsale.ChinaPlas.dao.ExhibitorIndustryDtl;
import com.adsale.ChinaPlas.dao.Industry;
import com.adsale.ChinaPlas.dao.SeminarInfo;
import com.adsale.ChinaPlas.dao.SeminarSpeaker;
import com.adsale.ChinaPlas.dao.FloorPlanCoordinate;

import com.adsale.ChinaPlas.dao.MainIconDao;
import com.adsale.ChinaPlas.dao.ApplicationIndustryDao;
import com.adsale.ChinaPlas.dao.ApplicationCompanyDao;
import com.adsale.ChinaPlas.dao.CountryDao;
import com.adsale.ChinaPlas.dao.ExhibitorDao;
import com.adsale.ChinaPlas.dao.ExhibitorUserUpdateDao;
import com.adsale.ChinaPlas.dao.FloorDao;
import com.adsale.ChinaPlas.dao.MapFloorDao;
import com.adsale.ChinaPlas.dao.NameCardDao;
import com.adsale.ChinaPlas.dao.NewsDao;
import com.adsale.ChinaPlas.dao.NewsLinkDao;
import com.adsale.ChinaPlas.dao.ProductIDDao;
import com.adsale.ChinaPlas.dao.ScheduleInfoDao;
import com.adsale.ChinaPlas.dao.UpdateDateDao;
import com.adsale.ChinaPlas.dao.WebContentDao;
import com.adsale.ChinaPlas.dao.BussinessMappingDao;
import com.adsale.ChinaPlas.dao.HistoryExhibitorDao;
import com.adsale.ChinaPlas.dao.UpdateCenterDao;
import com.adsale.ChinaPlas.dao.ExhibitorIndustryDtlDao;
import com.adsale.ChinaPlas.dao.IndustryDao;
import com.adsale.ChinaPlas.dao.SeminarInfoDao;
import com.adsale.ChinaPlas.dao.SeminarSpeakerDao;
import com.adsale.ChinaPlas.dao.FloorPlanCoordinateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mainIconDaoConfig;
    private final DaoConfig applicationIndustryDaoConfig;
    private final DaoConfig applicationCompanyDaoConfig;
    private final DaoConfig countryDaoConfig;
    private final DaoConfig exhibitorDaoConfig;
    private final DaoConfig exhibitorUserUpdateDaoConfig;
    private final DaoConfig floorDaoConfig;
    private final DaoConfig mapFloorDaoConfig;
    private final DaoConfig nameCardDaoConfig;
    private final DaoConfig newsDaoConfig;
    private final DaoConfig newsLinkDaoConfig;
    private final DaoConfig productIDDaoConfig;
    private final DaoConfig scheduleInfoDaoConfig;
    private final DaoConfig updateDateDaoConfig;
    private final DaoConfig webContentDaoConfig;
    private final DaoConfig bussinessMappingDaoConfig;
    private final DaoConfig historyExhibitorDaoConfig;
    private final DaoConfig updateCenterDaoConfig;
    private final DaoConfig exhibitorIndustryDtlDaoConfig;
    private final DaoConfig industryDaoConfig;
    private final DaoConfig seminarInfoDaoConfig;
    private final DaoConfig seminarSpeakerDaoConfig;
    private final DaoConfig floorPlanCoordinateDaoConfig;

    private final DaoConfig newProductAndCategoryDaoConfig;
    private final DaoConfig newProductInfoDaoConfig;
    private final DaoConfig newProductsAndApplicationDaoConfig;
    private final DaoConfig productApplicationDaoConfig;
    private final DaoConfig productImageDaoConfig;
    private final DaoConfig exhibitorZoneDaoConfig;
    private final DaoConfig zoneDaoConfig;

    private final MainIconDao mainIconDao;
    private final ApplicationIndustryDao applicationIndustryDao;
    private final ApplicationCompanyDao applicationCompanyDao;
    private final CountryDao countryDao;
    private final ExhibitorDao exhibitorDao;
    private final ExhibitorUserUpdateDao exhibitorUserUpdateDao;
    private final FloorDao floorDao;
    private final MapFloorDao mapFloorDao;
    private final NameCardDao nameCardDao;
    private final NewsDao newsDao;
    private final NewsLinkDao newsLinkDao;
    private final ProductIDDao productIDDao;
    private final ScheduleInfoDao scheduleInfoDao;
    private final UpdateDateDao updateDateDao;
    private final WebContentDao webContentDao;
    private final BussinessMappingDao bussinessMappingDao;
    private final HistoryExhibitorDao historyExhibitorDao;
    private final UpdateCenterDao updateCenterDao;
    private final ExhibitorIndustryDtlDao exhibitorIndustryDtlDao;
    private final IndustryDao industryDao;
    private final SeminarInfoDao seminarInfoDao;
    private final SeminarSpeakerDao seminarSpeakerDao;
    private final FloorPlanCoordinateDao floorPlanCoordinateDao;

    private final NewProductAndCategoryDao newProductAndCategoryDao;
    private final NewProductInfoDao newProductInfoDao;
    private final NewProductsAndApplicationDao newProductsAndApplicationDao;
    private final ProductApplicationDao productApplicationDao;
    private final ProductImageDao productImageDao;
    private final ExhibitorZoneDao exhibitorZoneDao;
    private final ZoneDao zoneDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mainIconDaoConfig = daoConfigMap.get(MainIconDao.class).clone();
        mainIconDaoConfig.initIdentityScope(type);

        applicationIndustryDaoConfig = daoConfigMap.get(ApplicationIndustryDao.class).clone();
        applicationIndustryDaoConfig.initIdentityScope(type);

        applicationCompanyDaoConfig = daoConfigMap.get(ApplicationCompanyDao.class).clone();
        applicationCompanyDaoConfig.initIdentityScope(type);

        countryDaoConfig = daoConfigMap.get(CountryDao.class).clone();
        countryDaoConfig.initIdentityScope(type);

        exhibitorDaoConfig = daoConfigMap.get(ExhibitorDao.class).clone();
        exhibitorDaoConfig.initIdentityScope(type);

        exhibitorUserUpdateDaoConfig = daoConfigMap.get(ExhibitorUserUpdateDao.class).clone();
        exhibitorUserUpdateDaoConfig.initIdentityScope(type);

        floorDaoConfig = daoConfigMap.get(FloorDao.class).clone();
        floorDaoConfig.initIdentityScope(type);

        mapFloorDaoConfig = daoConfigMap.get(MapFloorDao.class).clone();
        mapFloorDaoConfig.initIdentityScope(type);

        nameCardDaoConfig = daoConfigMap.get(NameCardDao.class).clone();
        nameCardDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        newsLinkDaoConfig = daoConfigMap.get(NewsLinkDao.class).clone();
        newsLinkDaoConfig.initIdentityScope(type);

        productIDDaoConfig = daoConfigMap.get(ProductIDDao.class).clone();
        productIDDaoConfig.initIdentityScope(type);

        scheduleInfoDaoConfig = daoConfigMap.get(ScheduleInfoDao.class).clone();
        scheduleInfoDaoConfig.initIdentityScope(type);

        updateDateDaoConfig = daoConfigMap.get(UpdateDateDao.class).clone();
        updateDateDaoConfig.initIdentityScope(type);

        webContentDaoConfig = daoConfigMap.get(WebContentDao.class).clone();
        webContentDaoConfig.initIdentityScope(type);

        bussinessMappingDaoConfig = daoConfigMap.get(BussinessMappingDao.class).clone();
        bussinessMappingDaoConfig.initIdentityScope(type);

        historyExhibitorDaoConfig = daoConfigMap.get(HistoryExhibitorDao.class).clone();
        historyExhibitorDaoConfig.initIdentityScope(type);

        updateCenterDaoConfig = daoConfigMap.get(UpdateCenterDao.class).clone();
        updateCenterDaoConfig.initIdentityScope(type);

        exhibitorIndustryDtlDaoConfig = daoConfigMap.get(ExhibitorIndustryDtlDao.class).clone();
        exhibitorIndustryDtlDaoConfig.initIdentityScope(type);

        industryDaoConfig = daoConfigMap.get(IndustryDao.class).clone();
        industryDaoConfig.initIdentityScope(type);

        seminarInfoDaoConfig = daoConfigMap.get(SeminarInfoDao.class).clone();
        seminarInfoDaoConfig.initIdentityScope(type);

        seminarSpeakerDaoConfig = daoConfigMap.get(SeminarSpeakerDao.class).clone();
        seminarSpeakerDaoConfig.initIdentityScope(type);

        floorPlanCoordinateDaoConfig = daoConfigMap.get(FloorPlanCoordinateDao.class).clone();
        floorPlanCoordinateDaoConfig.initIdentityScope(type);


        newProductAndCategoryDaoConfig = daoConfigMap.get(NewProductAndCategoryDao.class).clone();
        newProductAndCategoryDaoConfig.initIdentityScope(type);

        newProductInfoDaoConfig = daoConfigMap.get(NewProductInfoDao.class).clone();
        newProductInfoDaoConfig.initIdentityScope(type);

        newProductsAndApplicationDaoConfig = daoConfigMap.get(NewProductsAndApplicationDao.class).clone();
        newProductsAndApplicationDaoConfig.initIdentityScope(type);

        productApplicationDaoConfig = daoConfigMap.get(ProductApplicationDao.class).clone();
        productApplicationDaoConfig.initIdentityScope(type);

        productImageDaoConfig = daoConfigMap.get(ProductImageDao.class).clone();
        productImageDaoConfig.initIdentityScope(type);

        exhibitorZoneDaoConfig = daoConfigMap.get(ExhibitorZoneDao.class).clone();
        exhibitorZoneDaoConfig.initIdentityScope(type);

        zoneDaoConfig = daoConfigMap.get(ZoneDao.class).clone();
        zoneDaoConfig.initIdentityScope(type);

        mainIconDao = new MainIconDao(mainIconDaoConfig, this);
        applicationIndustryDao = new ApplicationIndustryDao(applicationIndustryDaoConfig, this);
        applicationCompanyDao = new ApplicationCompanyDao(applicationCompanyDaoConfig, this);
        countryDao = new CountryDao(countryDaoConfig, this);
        exhibitorDao = new ExhibitorDao(exhibitorDaoConfig, this);
        exhibitorUserUpdateDao = new ExhibitorUserUpdateDao(exhibitorUserUpdateDaoConfig, this);
        floorDao = new FloorDao(floorDaoConfig, this);
        mapFloorDao = new MapFloorDao(mapFloorDaoConfig, this);
        nameCardDao = new NameCardDao(nameCardDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);
        newsLinkDao = new NewsLinkDao(newsLinkDaoConfig, this);
        productIDDao = new ProductIDDao(productIDDaoConfig, this);
        scheduleInfoDao = new ScheduleInfoDao(scheduleInfoDaoConfig, this);
        updateDateDao = new UpdateDateDao(updateDateDaoConfig, this);
        webContentDao = new WebContentDao(webContentDaoConfig, this);
        bussinessMappingDao = new BussinessMappingDao(bussinessMappingDaoConfig, this);
        historyExhibitorDao = new HistoryExhibitorDao(historyExhibitorDaoConfig, this);
        updateCenterDao = new UpdateCenterDao(updateCenterDaoConfig, this);
        exhibitorIndustryDtlDao = new ExhibitorIndustryDtlDao(exhibitorIndustryDtlDaoConfig, this);
        industryDao = new IndustryDao(industryDaoConfig, this);
        seminarInfoDao = new SeminarInfoDao(seminarInfoDaoConfig, this);
        seminarSpeakerDao = new SeminarSpeakerDao(seminarSpeakerDaoConfig, this);
        floorPlanCoordinateDao = new FloorPlanCoordinateDao(floorPlanCoordinateDaoConfig, this);

        newProductAndCategoryDao = new NewProductAndCategoryDao(newProductAndCategoryDaoConfig, this);
        newProductInfoDao = new NewProductInfoDao(newProductInfoDaoConfig, this);
        newProductsAndApplicationDao = new NewProductsAndApplicationDao(newProductsAndApplicationDaoConfig, this);
        productApplicationDao = new ProductApplicationDao(productApplicationDaoConfig, this);
        productImageDao = new ProductImageDao(productImageDaoConfig, this);
        exhibitorZoneDao = new ExhibitorZoneDao(exhibitorZoneDaoConfig,this);
        zoneDao = new ZoneDao(zoneDaoConfig,this);


        registerDao(MainIcon.class, mainIconDao);
        registerDao(ApplicationIndustry.class, applicationIndustryDao);
        registerDao(ApplicationCompany.class, applicationCompanyDao);
        registerDao(Country.class, countryDao);
        registerDao(Exhibitor.class, exhibitorDao);
        registerDao(ExhibitorUserUpdate.class, exhibitorUserUpdateDao);
        registerDao(Floor.class, floorDao);
        registerDao(MapFloor.class, mapFloorDao);
        registerDao(NameCard.class, nameCardDao);
        registerDao(News.class, newsDao);
        registerDao(NewsLink.class, newsLinkDao);
        registerDao(ProductID.class, productIDDao);
        registerDao(ScheduleInfo.class, scheduleInfoDao);
        registerDao(UpdateDate.class, updateDateDao);
        registerDao(WebContent.class, webContentDao);
        registerDao(BussinessMapping.class, bussinessMappingDao);
        registerDao(HistoryExhibitor.class, historyExhibitorDao);
        registerDao(UpdateCenter.class, updateCenterDao);
        registerDao(ExhibitorIndustryDtl.class, exhibitorIndustryDtlDao);
        registerDao(Industry.class, industryDao);
        registerDao(SeminarInfo.class, seminarInfoDao);
        registerDao(SeminarSpeaker.class, seminarSpeakerDao);
        registerDao(FloorPlanCoordinate.class, floorPlanCoordinateDao);
        registerDao(NewProductAndCategory.class, newProductAndCategoryDao);
        registerDao(NewProductInfo.class, newProductInfoDao);
        registerDao(NewProductsAndApplication.class, newProductsAndApplicationDao);
        registerDao(ProductApplication.class, productApplicationDao);
        registerDao(ProductImage.class, productImageDao);
        registerDao(ExhibitorZone.class, exhibitorZoneDao);
        registerDao(Zone.class, zoneDao);
    }
    
    public void clear() {
        mainIconDaoConfig.getIdentityScope().clear();
        applicationIndustryDaoConfig.getIdentityScope().clear();
        applicationCompanyDaoConfig.getIdentityScope().clear();
        countryDaoConfig.getIdentityScope().clear();
        exhibitorDaoConfig.getIdentityScope().clear();
        exhibitorUserUpdateDaoConfig.getIdentityScope().clear();
        floorDaoConfig.getIdentityScope().clear();
        mapFloorDaoConfig.getIdentityScope().clear();
        nameCardDaoConfig.getIdentityScope().clear();
        newsDaoConfig.getIdentityScope().clear();
        newsLinkDaoConfig.getIdentityScope().clear();
        productIDDaoConfig.getIdentityScope().clear();
        scheduleInfoDaoConfig.getIdentityScope().clear();
        updateDateDaoConfig.getIdentityScope().clear();
        webContentDaoConfig.getIdentityScope().clear();
        bussinessMappingDaoConfig.getIdentityScope().clear();
        historyExhibitorDaoConfig.getIdentityScope().clear();
        updateCenterDaoConfig.getIdentityScope().clear();
        exhibitorIndustryDtlDaoConfig.getIdentityScope().clear();
        industryDaoConfig.getIdentityScope().clear();
        seminarInfoDaoConfig.getIdentityScope().clear();
        seminarSpeakerDaoConfig.getIdentityScope().clear();
        floorPlanCoordinateDaoConfig.getIdentityScope().clear();
        newProductAndCategoryDaoConfig.getIdentityScope().clear();
        newProductInfoDaoConfig.getIdentityScope().clear();
        newProductsAndApplicationDaoConfig.getIdentityScope().clear();
        productApplicationDaoConfig.getIdentityScope().clear();
        productImageDaoConfig.getIdentityScope().clear();
        exhibitorZoneDaoConfig.getIdentityScope().clear();
        zoneDaoConfig.getIdentityScope().clear();
    }

    public MainIconDao getMainIconDao() {
        return mainIconDao;
    }

    public ApplicationIndustryDao getApplicationIndustryDao() {
        return applicationIndustryDao;
    }

    public ApplicationCompanyDao getApplicationCompanyDao() {
        return applicationCompanyDao;
    }

    public CountryDao getCountryDao() {
        return countryDao;
    }

    public ExhibitorDao getExhibitorDao() {
        return exhibitorDao;
    }

    public ExhibitorUserUpdateDao getExhibitorUserUpdateDao() {
        return exhibitorUserUpdateDao;
    }

    public FloorDao getFloorDao() {
        return floorDao;
    }

    public MapFloorDao getMapFloorDao() {
        return mapFloorDao;
    }

    public NameCardDao getNameCardDao() {
        return nameCardDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public NewsLinkDao getNewsLinkDao() {
        return newsLinkDao;
    }

    public ProductIDDao getProductIDDao() {
        return productIDDao;
    }

    public ScheduleInfoDao getScheduleInfoDao() {
        return scheduleInfoDao;
    }

    public UpdateDateDao getUpdateDateDao() {
        return updateDateDao;
    }

    public WebContentDao getWebContentDao() {
        return webContentDao;
    }

    public BussinessMappingDao getBussinessMappingDao() {
        return bussinessMappingDao;
    }

    public HistoryExhibitorDao getHistoryExhibitorDao() {
        return historyExhibitorDao;
    }

    public UpdateCenterDao getUpdateCenterDao() {
        return updateCenterDao;
    }

    public ExhibitorIndustryDtlDao getExhibitorIndustryDtlDao() {
        return exhibitorIndustryDtlDao;
    }

    public IndustryDao getIndustryDao() {
        return industryDao;
    }

    public SeminarInfoDao getSeminarInfoDao() {
        return seminarInfoDao;
    }

    public SeminarSpeakerDao getSeminarSpeakerDao() {
        return seminarSpeakerDao;
    }

    public FloorPlanCoordinateDao getFloorPlanCoordinateDao() {
        return floorPlanCoordinateDao;
    }

    public NewProductAndCategoryDao getNewProductAndCategoryDao() {
        return newProductAndCategoryDao;
    }

    public NewProductInfoDao getNewProductInfoDao() {
        return newProductInfoDao;
    }

    public NewProductsAndApplicationDao getNewProductsAndApplicationDao() {
        return newProductsAndApplicationDao;
    }

    public ProductApplicationDao getProductApplicationDao() {
        return productApplicationDao;
    }

    public ProductImageDao getProductImageDao() {
        return productImageDao;
    }

    public ExhibitorZoneDao getExhibitorZoneDao() {
        return exhibitorZoneDao;
    }

    public ZoneDao getZoneDao() {
        return zoneDao;
    }
}
