package com.adsale.ChinaPlas.dao;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EXHIBITOR__TABLE__TEMP".
 */
public class EXHIBITOR_TABLE_TEMP {

    private String COMPANY_ID;
    private Integer IS_FAVOURITE;
    private String NOTE;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public EXHIBITOR_TABLE_TEMP() {
    }

    public EXHIBITOR_TABLE_TEMP(String COMPANY_ID) {
        this.COMPANY_ID = COMPANY_ID;
    }

    public EXHIBITOR_TABLE_TEMP(String COMPANY_ID, Integer IS_FAVOURITE, String NOTE) {
        this.COMPANY_ID = COMPANY_ID;
        this.IS_FAVOURITE = IS_FAVOURITE;
        this.NOTE = NOTE;
    }

    public String getCOMPANY_ID() {
        return COMPANY_ID;
    }

    public void setCOMPANY_ID(String COMPANY_ID) {
        this.COMPANY_ID = COMPANY_ID;
    }

    public Integer getIS_FAVOURITE() {
        return IS_FAVOURITE;
    }

    public void setIS_FAVOURITE(Integer IS_FAVOURITE) {
        this.IS_FAVOURITE = IS_FAVOURITE;
    }

    public String getNOTE() {
        return NOTE;
    }

    public void setNOTE(String NOTE) {
        this.NOTE = NOTE;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
