package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EXHIBITOR_USER_UPDATE".
 */
public class ExhibitorUserUpdate {

    private String CompanyID;
    private String IsFavourite;
    private String Note;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ExhibitorUserUpdate() {
    }

    public ExhibitorUserUpdate(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public ExhibitorUserUpdate(String CompanyID, String IsFavourite, String Note) {
        this.CompanyID = CompanyID;
        this.IsFavourite = IsFavourite;
        this.Note = Note;
    }

    public String getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public String getIsFavourite() {
        return IsFavourite;
    }

    public void setIsFavourite(String IsFavourite) {
        this.IsFavourite = IsFavourite;
    }

    public String getNote() {
        return Note;
    }

    public void setNote(String Note) {
        this.Note = Note;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
