package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "EXHIBITOR_ZONE".
 */
public class ExhibitorZone implements Parcelable {

    private String CompanyID;
    private String ThemeZoneCode;
    private Boolean IsDelete;
    private String createdAt;
    private String updatedAt;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ExhibitorZone() {
    }

    public ExhibitorZone(String CompanyID, String ThemeZoneCode, Boolean IsDelete, String createdAt, String updatedAt) {
        this.CompanyID = CompanyID;
        this.ThemeZoneCode = ThemeZoneCode;
        this.IsDelete = IsDelete;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public String getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public String getThemeZoneCode() {
        return ThemeZoneCode;
    }

    public void setThemeZoneCode(String ThemeZoneCode) {
        this.ThemeZoneCode = ThemeZoneCode;
    }

    public Boolean getIsDelete() {
        return IsDelete;
    }

    public void setIsDelete(Boolean IsDelete) {
        this.IsDelete = IsDelete;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    // KEEP METHODS - put your custom methods here
    public void parser(String[] strings) {
        this.ThemeZoneCode = strings[0];
        this.CompanyID = strings[1];
    }



    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.CompanyID);
        dest.writeString(this.ThemeZoneCode);
        dest.writeValue(this.IsDelete);
        dest.writeString(this.createdAt);
        dest.writeString(this.updatedAt);
    }

    protected ExhibitorZone(Parcel in) {
        this.CompanyID = in.readString();
        this.ThemeZoneCode = in.readString();
        this.IsDelete = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.createdAt = in.readString();
        this.updatedAt = in.readString();
    }

    public static final Parcelable.Creator<ExhibitorZone> CREATOR = new Parcelable.Creator<ExhibitorZone>() {
        public ExhibitorZone createFromParcel(Parcel source) {
            return new ExhibitorZone(source);
        }

        public ExhibitorZone[] newArray(int size) {
            return new ExhibitorZone[size];
        }
    };
}
