package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FLOOR".
 */
public class Floor {

    private String FloorID;
    private String FloorNameTW;
    private String FloorNameEN;
    private String FloorNameCN;
    private Integer SEQ;

    // KEEP FIELDS - put your custom fields here
    public int exhibitorCount;
    // KEEP FIELDS END

    public Floor() {
    }

    public Floor(String FloorID) {
        this.FloorID = FloorID;
    }

    public Floor(String FloorID, String FloorNameTW, String FloorNameEN, String FloorNameCN, Integer SEQ) {
        this.FloorID = FloorID;
        this.FloorNameTW = FloorNameTW;
        this.FloorNameEN = FloorNameEN;
        this.FloorNameCN = FloorNameCN;
        this.SEQ = SEQ;
    }

    public String getFloorID() {
        return FloorID;
    }

    public void setFloorID(String FloorID) {
        this.FloorID = FloorID;
    }

    public String getFloorNameTW() {
        return FloorNameTW;
    }

    public void setFloorNameTW(String FloorNameTW) {
        this.FloorNameTW = FloorNameTW;
    }

    public String getFloorNameEN() {
        return FloorNameEN;
    }

    public void setFloorNameEN(String FloorNameEN) {
        this.FloorNameEN = FloorNameEN;
    }

    public String getFloorNameCN() {
        return FloorNameCN;
    }

    public void setFloorNameCN(String FloorNameCN) {
        this.FloorNameCN = FloorNameCN;
    }

    public Integer getSEQ() {
        return SEQ;
    }

    public void setSEQ(Integer SEQ) {
        this.SEQ = SEQ;
    }

    // KEEP METHODS - put your custom methods here
    public String getFloorName(int language){
    	if(language==0){
    		return FloorNameTW;
    	}else if(language==1){
    		return FloorNameEN;
    	}else{
    		return FloorNameCN;
    	}
    }

    public void parser(String[] strings) {
        this.FloorID = strings[0];
        this.FloorNameEN = strings[1];
        this.FloorNameTW = strings[2];
        this.FloorNameCN = strings[3];
        this.SEQ =Integer.valueOf(strings[4]);
    }


    // KEEP METHODS END

}
