package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HALL".
 */
public class Hall {

    private String HallID;
    private String HallEng;
    private String HallTC;
    private String HallSC;
    private String SEQ;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Hall() {
    }

    public Hall(String HallID) {
        this.HallID = HallID;
    }

    public Hall(String HallID, String HallEng, String HallTC, String HallSC, String SEQ) {
        this.HallID = HallID;
        this.HallEng = HallEng;
        this.HallTC = HallTC;
        this.HallSC = HallSC;
        this.SEQ = SEQ;
    }

    public String getHallID() {
        return HallID;
    }

    public void setHallID(String HallID) {
        this.HallID = HallID;
    }

    public String getHallEng() {
        return HallEng;
    }

    public void setHallEng(String HallEng) {
        this.HallEng = HallEng;
    }

    public String getHallTC() {
        return HallTC;
    }

    public void setHallTC(String HallTC) {
        this.HallTC = HallTC;
    }

    public String getHallSC() {
        return HallSC;
    }

    public void setHallSC(String HallSC) {
        this.HallSC = HallSC;
    }

    public String getSEQ() {
        return SEQ;
    }

    public void setSEQ(String SEQ) {
        this.SEQ = SEQ;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
