package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.databinding.ObservableInt;

import com.adsale.ChinaPlas.R;
import com.adsale.ChinaPlas.utils.AppUtil;

import static com.adsale.ChinaPlas.utils.AppUtil.getName;

/**
 * Entity mapped to table "HISTORY_EXHIBITOR".
 */
public class HistoryExhibitor {

    private Long id;
    private String CompanyID;
    private String CompanyNameEN;
    private String CompanyNameCN;
    private String CompanyNameTW;
    private String Booth;
    private String Time;

    // KEEP FIELDS - put your custom fields here

    /**
     * 1=Today,0=Yesterday,-1=Past
     */
//    public int status;

    public final ObservableInt status = new ObservableInt();
    // KEEP FIELDS END

//    public int getLabel() {
//        if (status == 1) {
//            return R.string.today;
//        } else if (status == 0) {
//            return R.string.yesterday;
//        } else {
//            return R.string.past_records;
//        }
//    }

    public HistoryExhibitor() {
    }

    public HistoryExhibitor(Long id) {
        this.id = id;
    }

    public HistoryExhibitor(Long id, String CompanyID, String CompanyNameEN, String CompanyNameCN, String CompanyNameTW, String Booth, String Time) {
        this.id = id;
        this.CompanyID = CompanyID;
        this.CompanyNameEN = CompanyNameEN;
        this.CompanyNameCN = CompanyNameCN;
        this.CompanyNameTW = CompanyNameTW;
        this.Booth = Booth;
        this.Time = Time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public String getCompanyNameEN() {
        return CompanyNameEN;
    }

    public void setCompanyNameEN(String CompanyNameEN) {
        this.CompanyNameEN = CompanyNameEN;
    }

    public String getCompanyNameCN() {
        return CompanyNameCN;
    }

    public void setCompanyNameCN(String CompanyNameCN) {
        this.CompanyNameCN = CompanyNameCN;
    }

    public String getCompanyNameTW() {
        return CompanyNameTW;
    }

    public void setCompanyNameTW(String CompanyNameTW) {
        this.CompanyNameTW = CompanyNameTW;
    }

    public String getBooth() {
        return Booth;
    }

    public void setBooth(String Booth) {
        this.Booth = Booth;
    }

    public String getTime() {
        return Time;
    }

    public void setTime(String Time) {
        this.Time = Time;
    }

    // KEEP METHODS - put your custom methods here

    /**
     * 展商浏览次数/访问频率
     */
    public int frequency;

    public String getFrequency() {
        return "" + frequency;
    }


    @Override
    public String toString() {
        return "HistoryExhibitor [id=" + id + ", CompanyID=" + CompanyID + ", CompanyNameEN=" + CompanyNameEN
                + ", CompanyNameCN=" + CompanyNameCN + ", CompanyNameTW=" + CompanyNameTW + ", Booth=" + Booth
                + ", Time=" + Time + ", status=" + status + ", frequency=" + frequency + "]";
    }


    public String getCompanyName() {
        return AppUtil.getName(CompanyNameTW, CompanyNameEN, CompanyNameCN);
    }
    // KEEP METHODS END

}
