package com.adsale.ChinaPlas.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.adsale.ChinaPlas.dao.Industry;

import static com.adsale.ChinaPlas.dao.IndustryDao.Properties.EN_SORT;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "INDUSTRY".
 */
public class IndustryDao extends AbstractDao<Industry, String> {

    public static final String TABLENAME = "INDUSTRY";

    /**
     * Properties of entity Industry.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CatalogProductSubID = new Property(0, String.class, "CatalogProductSubID", true, "CATALOG_PRODUCT_SUB_ID");
        public final static Property CatEng = new Property(1, String.class, "CatEng", false, "CAT_ENG");
        public final static Property CatTC = new Property(2, String.class, "CatTC", false, "CAT_TC");
        public final static Property CatSC = new Property(3, String.class, "CatSC", false, "CAT_SC");
        public final static Property TCStroke = new Property(4, Integer.class, "TCStroke", false, "TCSTROKE");
        public final static Property SCPY = new Property(5, String.class, "SCPY", false, "SCPY");
        public final static Property IsSelected = new Property(6, Boolean.class, "IsSelected", false, "IS_SELECTED");
        public final static Property EN_SORT = new Property(7, String.class, "EN_SORT", false, "EN_SORT");
    }

    ;


    public IndustryDao(DaoConfig config) {
        super(config);
    }

    public IndustryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"INDUSTRY\" (" + //
                "\"CATALOG_PRODUCT_SUB_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: CatalogProductSubID
                "\"CAT_ENG\" TEXT," + // 1: CatEng
                "\"CAT_TC\" TEXT," + // 2: CatTC
                "\"CAT_SC\" TEXT," + // 3: CatSC
                "\"TCSTROKE\" INTEGER," + // 4: TCStroke
                "\"SCPY\" TEXT," + // 5: SCPY
                "\"IS_SELECTED\" INTEGER);"); // 6: IsSelected
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INDUSTRY\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, Industry entity) {
        stmt.clearBindings();

        String CatalogProductSubID = entity.getCatalogProductSubID();
        if (CatalogProductSubID != null) {
            stmt.bindString(1, CatalogProductSubID);
        }

        String CatEng = entity.getCatEng();
        if (CatEng != null) {
            stmt.bindString(2, CatEng);
        }

        String CatTC = entity.getCatTC();
        if (CatTC != null) {
            stmt.bindString(3, CatTC);
        }

        String CatSC = entity.getCatSC();
        if (CatSC != null) {
            stmt.bindString(4, CatSC);
        }

        Integer TCStroke = entity.getTCStroke();
        if (TCStroke != null) {
            stmt.bindLong(5, TCStroke);
        }

        String SCPY = entity.getSCPY();
        if (SCPY != null) {
            stmt.bindString(6, SCPY);
        }

        Boolean IsSelected = entity.getIsSelected();
        if (IsSelected != null) {
            stmt.bindLong(7, IsSelected ? 1L : 0L);
        }

        String EN_SORT = entity.getEN_SORT();
        if (EN_SORT != null) {
            stmt.bindString(8, EN_SORT);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Industry readEntity(Cursor cursor, int offset) {
        Industry entity = new Industry( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // CatalogProductSubID
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // CatEng
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // CatTC
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // CatSC
                cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // TCStroke
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // SCPY
                cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // IsSelected
                cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // EN_SORT
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, Industry entity, int offset) {
        entity.setCatalogProductSubID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCatEng(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCatTC(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCatSC(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTCStroke(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setSCPY(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsSelected(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setEN_SORT(cursor.isNull(offset + 7) ? null : cursor.getString(offset +7));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected String updateKeyAfterInsert(Industry entity, long rowId) {
        return entity.getCatalogProductSubID();
    }

    /**
     * @inheritdoc
     */
    @Override
    public String getKey(Industry entity) {
        if (entity != null) {
            return entity.getCatalogProductSubID();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
