package com.adsale.ChinaPlas.dao;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "NAME__CARD__TEMP".
 */
public class NAME_CARD_TEMP {

    private String DEVICE_ID;
    private int COMPANY;

    private String NAME;

    private String TITLE;

    private String PHONE;

    private String EMAIL;
    private Integer QQ;
    private Integer WE_CHAT;
    private String UPDATE_DATE_TIME;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NAME_CARD_TEMP() {
    }

    public NAME_CARD_TEMP(String DEVICE_ID) {
        this.DEVICE_ID = DEVICE_ID;
    }

    public NAME_CARD_TEMP(String DEVICE_ID, int COMPANY, String NAME, String TITLE, String PHONE, String EMAIL, Integer QQ, Integer WE_CHAT, String UPDATE_DATE_TIME) {
        this.DEVICE_ID = DEVICE_ID;
        this.COMPANY = COMPANY;
        this.NAME = NAME;
        this.TITLE = TITLE;
        this.PHONE = PHONE;
        this.EMAIL = EMAIL;
        this.QQ = QQ;
        this.WE_CHAT = WE_CHAT;
        this.UPDATE_DATE_TIME = UPDATE_DATE_TIME;
    }

    public String getDEVICE_ID() {
        return DEVICE_ID;
    }

    public void setDEVICE_ID(String DEVICE_ID) {
        this.DEVICE_ID = DEVICE_ID;
    }

    public int getCOMPANY() {
        return COMPANY;
    }

    public void setCOMPANY(int COMPANY) {
        this.COMPANY = COMPANY;
    }

   
    public String getNAME() {
        return NAME;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNAME( String NAME) {
        this.NAME = NAME;
    }

    public String getTITLE() {
        return TITLE;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE;
    }

    public String getPHONE() {
        return PHONE;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPHONE(String PHONE) {
        this.PHONE = PHONE;
    }

    public String getEMAIL() {
        return EMAIL;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEMAIL( String EMAIL) {
        this.EMAIL = EMAIL;
    }

    public Integer getQQ() {
        return QQ;
    }

    public void setQQ(Integer QQ) {
        this.QQ = QQ;
    }

    public Integer getWE_CHAT() {
        return WE_CHAT;
    }

    public void setWE_CHAT(Integer WE_CHAT) {
        this.WE_CHAT = WE_CHAT;
    }

    public String getUPDATE_DATE_TIME() {
        return UPDATE_DATE_TIME;
    }

    public void setUPDATE_DATE_TIME(String UPDATE_DATE_TIME) {
        this.UPDATE_DATE_TIME = UPDATE_DATE_TIME;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
