package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "NAME_CARD".
 */
public class NameCard implements Parcelable {

    private String DeviceId;
    /** Not-null value. */
    private String Company;
    /** Not-null value. */
    private String Name;
    /** Not-null value. */
    private String Title;
    /** Not-null value. */
    private String Phone;
    /** Not-null value. */
    private String Email;
    private String QQ;
    private String WeChat;
    private String UpdateDateTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NameCard() {
    }

    public NameCard(String DeviceId) {
        this.DeviceId = DeviceId;
    }

    public NameCard(String DeviceId, String Company, String Name, String Title, String Phone, String Email, String QQ,String WeChat, String UpdateDateTime) {
        this.DeviceId = DeviceId;
        this.Company = Company;
        this.Name = Name;
        this.Title = Title;
        this.Phone = Phone;
        this.Email = Email;
        this.QQ = QQ;
        this.WeChat = WeChat;
        this.UpdateDateTime = UpdateDateTime;
    }

    public String getDeviceId() {
        return DeviceId;
    }

    public void setDeviceId(String DeviceId) {
        this.DeviceId = DeviceId;
    }

    /** Not-null value. */
    public String getCompany() {
        return Company;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompany(String Company) {
        this.Company = Company;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    /** Not-null value. */
    public String getTitle() {
        return Title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String Title) {
        this.Title = Title;
    }

    /** Not-null value. */
    public String getPhone() {
        return Phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    /** Not-null value. */
    public String getEmail() {
        return Email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getQQ() {
        return QQ;
    }

    public String getWeChat() {
        return WeChat;
    }

    public void setQQ(String QQ) {
        this.QQ = QQ;
    }

    public void setWeChat(String weChat) {
        this.WeChat = weChat;
    }

    public String getUpdateDateTime() {
        return UpdateDateTime;
    }

    public void setUpdateDateTime(String UpdateDateTime) {
        this.UpdateDateTime = UpdateDateTime;
    }

    // KEEP METHODS - put your custom methods here
    @Override
	public String toString() {
		return "NameCard [DeviceId=" + DeviceId + ", Company=" + Company + ", Name=" + Name + ", Title=" + Title + ", Phone=" + Phone + ", Email="
				+ Email + ", QQ=" + QQ +", WeChat=" + WeChat + ", UpdateDateTime=" + UpdateDateTime + "]";
	}

//    public String[] getColumnName(int language){
//        if(language==0){
//            return new String[]{""};//NAME,COMPANY,TITLE,PHONE,EMAIL,QQ,WE_CHAT
//        }
//    }




    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.DeviceId);
        dest.writeString(this.Company);
        dest.writeString(this.Name);
        dest.writeString(this.Title);
        dest.writeString(this.Phone);
        dest.writeString(this.Email);
        dest.writeString(this.QQ);
        dest.writeString(this.WeChat);
        dest.writeString(this.UpdateDateTime);
    }

    protected NameCard(Parcel in) {
        this.DeviceId = in.readString();
        this.Company = in.readString();
        this.Name = in.readString();
        this.Title = in.readString();
        this.Phone = in.readString();
        this.Email = in.readString();
        this.QQ = in.readString();
        this.WeChat = in.readString();
        this.UpdateDateTime = in.readString();
    }

    public static final Creator<NameCard> CREATOR = new Creator<NameCard>() {
        public NameCard createFromParcel(Parcel source) {
            return new NameCard(source);
        }

        public NameCard[] newArray(int size) {
            return new NameCard[size];
        }
    };
}
