package com.adsale.ChinaPlas.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "NEW_CATEGORY_SUB".
*/
public class NewCategorySubDao extends AbstractDao<NewCategorySub, Void> {
    //MainTypeId|SubNameEn|SubNameTc|SubNameSc|CategoryId|OrderId
    public static final String TABLENAME = "NEW_CATEGORY_SUB";

    /**
     * Properties of entity NewCategorySub.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property MainTypeId = new Property(0, String.class, "MainTypeId", false, "MainTypeId");
        public final static Property SubNameEn = new Property(1, String.class, "SubNameEn", false, "SubNameEn");
        public final static Property SubNameTc = new Property(2, String.class, "SubNameTc", false, "SubNameTc");
        public final static Property SubNameSc = new Property(3, String.class, "SubNameSc", false, "SubNameSc");
        public final static Property CategoryId = new Property(4, String.class, "CategoryId", false, "CategoryId");
        public final static Property OrderId = new Property(5, int.class, "OrderId", false, "OrderId");
    };


    public NewCategorySubDao(DaoConfig config) {
        super(config);
    }

    public NewCategorySubDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEW_CATEGORY_SUB\" (" + //
                "\"MainTypeId\" TEXT," + // 0: Spot
                "\"SubNameEn\" TEXT," + // 0: Spot
                "\"SubNameTc\" TEXT," + // 0: Spot
                "\"SubNameSc\" TEXT," + // 0: Spot
                "\"CategoryId\" TEXT," + // 0: Spot
                "\"OrderId\" INTEGER);"); // 1: RID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEW_CATEGORY_SUB\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, NewCategorySub entity) {
        stmt.clearBindings();
 
        String MainTypeId = entity.getMainTypeId();
        if (MainTypeId != null) {
            stmt.bindString(1, MainTypeId);
        }
 
        String SubNameEn = entity.getSubNameEn();
        if (SubNameEn != null) {
            stmt.bindString(2, SubNameEn);
        }

        String SubNameTc = entity.getSubNameTc();
        if (SubNameTc != null) {
            stmt.bindString(3, SubNameTc);
        }

        String SubNameSc = entity.getSubNameSc();
        if (SubNameSc != null) {
            stmt.bindString(4, SubNameSc);
        }

        String CategoryId = entity.getCategoryId();
        if (CategoryId != null) {
            stmt.bindString(5, CategoryId);
        }

        stmt.bindLong(6, entity.getOrderId());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public NewCategorySub readEntity(Cursor cursor, int offset) {
        NewCategorySub entity = new NewCategorySub( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // DEVICE_ID
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // DEVICE_ID
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // DEVICE_ID
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // DEVICE_ID
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // DEVICE_ID
              cursor.getInt(offset + 5) // DEVICE_ID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, NewCategorySub entity, int offset) {
        entity.setMainTypeId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSubNameEn(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSubNameTc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSubNameSc(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCategoryId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setOrderId(cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(NewCategorySub entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(NewCategorySub entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
