package com.adsale.ChinaPlas.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "NEW_PRODUCTS_ID".
*/
public class NewProductsIDDao extends AbstractDao<NewProductsID, Void> {

    public static final String TABLENAME = "NEW_PRODUCTS_ID";

    /**
     * Properties of entity NewProductsID.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Spot = new Property(0, String.class, "Spot", false, "SPOT");
        public final static Property RID = new Property(1, String.class, "RID", false, "RID");
    };


    public NewProductsIDDao(DaoConfig config) {
        super(config);
    }
    
    public NewProductsIDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEW_PRODUCTS_ID\" (" + //
                "\"SPOT\" TEXT," + // 0: Spot
                "\"RID\" TEXT);"); // 1: RID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEW_PRODUCTS_ID\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, NewProductsID entity) {
        stmt.clearBindings();
 
        String Spot = entity.getSpot();
        if (Spot != null) {
            stmt.bindString(1, Spot);
        }
 
        String RID = entity.getRID();
        if (RID != null) {
            stmt.bindString(2, RID);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public NewProductsID readEntity(Cursor cursor, int offset) {
        NewProductsID entity = new NewProductsID( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Spot
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // RID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, NewProductsID entity, int offset) {
        entity.setSpot(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setRID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(NewProductsID entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(NewProductsID entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
