package com.adsale.ChinaPlas.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.adsale.ChinaPlas.dao.NewsLink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWS_LINK".
*/
public class NewsLinkDao extends AbstractDao<NewsLink, String> {

    public static final String TABLENAME = "NewsLink";

    /**
     * Properties of entity NewsLink.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property LinkID = new Property(0, String.class, "LinkID", true, "LinkID");
        public final static Property NewsID = new Property(1, String.class, "NewsID", false, "NewsID");
        public final static Property Photo = new Property(2, String.class, "Photo", false, "Photo");
        public final static Property Title = new Property(3, String.class, "Title", false, "Title");
        public final static Property Link = new Property(4, String.class, "Link", false, "Link");
        public final static Property SEQ = new Property(5, String.class, "SEQ", false, "SEQ");
        public final static Property CreatedAt = new Property(6, String.class, "createdAt", false, "createdAt");
        public final static Property UpdatedAt = new Property(7, String.class, "updatedAt", false, "updatedAt");
    };


    public NewsLinkDao(DaoConfig config) {
        super(config);
    }
    
    public NewsLinkDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS_LINK\" (" + //
                "\"LINK_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: LinkID
                "\"NEWS_ID\" TEXT NOT NULL ," + // 1: NewsID
                "\"PHOTO\" TEXT," + // 2: Photo
                "\"TITLE\" TEXT," + // 3: Title
                "\"LINK\" TEXT," + // 4: Link
                "\"SEQ\" TEXT," + // 5: SEQ
                "\"CREATE_DATE_TIME\" TEXT NOT NULL ," + // 6: CreateDateTime
                "\"UPDATE_DATE_TIME\" TEXT NOT NULL ," + // 7: UpdateDateTime
                "\"RECORD_TIME_STAMP\" TEXT NOT NULL );"); // 8: RecordTimeStamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS_LINK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, NewsLink entity) {
        stmt.clearBindings();
 
        String LinkID = entity.getLinkID();
        if (LinkID != null) {
            stmt.bindString(1, LinkID);
        }
        stmt.bindString(2, entity.getNewsID());
 
        String Photo = entity.getPhoto();
        if (Photo != null) {
            stmt.bindString(3, Photo);
        }
 
        String Title = entity.getTitle();
        if (Title != null) {
            stmt.bindString(4, Title);
        }
 
        String Link = entity.getLink();
        if (Link != null) {
            stmt.bindString(5, Link);
        }
 
        String SEQ = entity.getSEQ();
        if (SEQ != null) {
            stmt.bindString(6, SEQ);
        }
        stmt.bindString(7, entity.getCreateDateTime());
        stmt.bindString(8, entity.getUpdateDateTime());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public NewsLink readEntity(Cursor cursor, int offset) {
        NewsLink entity = new NewsLink( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // LinkID
            cursor.getString(offset + 1), // NewsID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Photo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Link
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // SEQ
            cursor.getString(offset + 6), // CreateDateTime
            cursor.getString(offset + 7) // UpdateDateTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, NewsLink entity, int offset) {
        entity.setLinkID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNewsID(cursor.getString(offset + 1));
        entity.setPhoto(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLink(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSEQ(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCreateDateTime(cursor.getString(offset + 6));
        entity.setUpdateDateTime(cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(NewsLink entity, long rowId) {
        return entity.getLinkID();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(NewsLink entity) {
        if(entity != null) {
            return entity.getLinkID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
