package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "NEWS".
 */
public class News implements Parcelable {

    private String NewsID;
    private Integer LType;
    private String Logo;
    private String ShareLink;
    private String Title;
    private String Description;
    /**
     * Not-null value.
     */
    private String createdAt;
    /**
     * Not-null value.
     */
    private String updatedAt;
    private String PublishDate;

    // KEEP FIELDS - put your custom fields here
    private boolean IsDelete;


    // KEEP FIELDS END

    public News() {
    }

    public News(String NewsID) {
        this.NewsID = NewsID;
    }

    public News(String NewsID, Integer LType, String Logo, String ShareLink, String Title, String Description, String PublishDate,String CreateDateTime, String UpdateDateTime, Boolean IsDelete) {
        this.NewsID = NewsID;
        this.LType = LType;
        this.Logo = Logo;
        this.ShareLink = ShareLink;
        this.Title = Title;
        this.Description = Description;
        this.PublishDate = PublishDate;
        this.createdAt = CreateDateTime;
        this.updatedAt = UpdateDateTime;
        this.IsDelete = IsDelete;
    }

    public Boolean getIsDelete() {
        return IsDelete;
    }

    public void setIsDelete(Boolean isDelete) {
        IsDelete = isDelete;
    }

    public String getNewsID() {
        return NewsID;
    }

    public void setNewsID(String NewsID) {
        this.NewsID = NewsID;
    }

    public Integer getLType() {
        return LType;
    }

    public void setLType(Integer LType) {
        this.LType = LType;
    }

    public String getLogo() {
        return Logo;
    }

    public void setLogo(String Logo) {
        this.Logo = Logo;
    }

    public String getShareLink() {
        return ShareLink;
    }

    public void setShareLink(String ShareLink) {
        this.ShareLink = ShareLink;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    /**
     * Not-null value.
     */
    public String getCreateDateTime() {
        return createdAt;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setCreateDateTime(String CreateDateTime) {
        this.createdAt = CreateDateTime;
    }

    /**
     * Not-null value.
     */
    public String getUpdateDateTime() {
        return updatedAt;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUpdateDateTime(String UpdateDateTime) {
        this.updatedAt = UpdateDateTime;
    }

    public String getPublishDate() {
        return PublishDate;
    }

    public void setPublishDate(String publishDate) {
        PublishDate = publishDate;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "News{" +
                "NewsID='" + NewsID + '\'' +
//                ", LType=" + LType +
//                ", Logo='" + Logo + '\'' +
//                ", ShareLink='" + ShareLink + '\'' +
//                ", Title='" + Title + '\'' +
//                ", Description='" + Description + '\'' +
//                ", PublishDate='" + PublishDate + '\'' +
//                ", CreateDateTime='" + createdAt + '\'' +
//                ", UpdateDateTime='" + updatedAt + '\'' +
                '}';
    }

    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.NewsID);
        dest.writeValue(this.LType);
        dest.writeString(this.Logo);
        dest.writeString(this.ShareLink);
        dest.writeString(this.Title);
        dest.writeString(this.Description);
        dest.writeString(this.PublishDate);
        dest.writeString(this.createdAt);
        dest.writeString(this.updatedAt);
    }

    protected News(Parcel in) {
        this.NewsID = in.readString();
        this.LType = (Integer) in.readValue(Integer.class.getClassLoader());
        this.Logo = in.readString();
        this.ShareLink = in.readString();
        this.Title = in.readString();
        this.Description = in.readString();
        this.PublishDate = in.readString();
        this.createdAt= in.readString();
        this.updatedAt = in.readString();
    }

    public static final Parcelable.Creator<News> CREATOR = new Parcelable.Creator<News>() {
        public News createFromParcel(Parcel source) {
            return new News(source);
        }

        public News[] newArray(int size) {
            return new News[size];
        }
    };
}
