package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRODUCT_APPLICATION".
 */
public class ProductApplication {

    private String IndustryID;
    private String NameEn;
    private String NameEnShort;
    private String NameTc;
    private String NameSc;
    private String Ordering;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ProductApplication() {
    }

    public ProductApplication(String IndustryID, String NameEn, String NameEnShort, String NameTc, String NameSc, String Ordering) {
        this.IndustryID = IndustryID;
        this.NameEn = NameEn;
        this.NameEnShort = NameEnShort;
        this.NameTc = NameTc;
        this.NameSc = NameSc;
        this.Ordering = Ordering;
    }

    public String getIndustryID() {
        return IndustryID;
    }

    public void setIndustryID(String IndustryID) {
        this.IndustryID = IndustryID;
    }

    public String getNameEn() {
        return NameEn;
    }

    public void setNameEn(String NameEn) {
        this.NameEn = NameEn;
    }

    public String getNameEnShort() {
        return NameEnShort;
    }

    public void setNameEnShort(String NameEnShort) {
        this.NameEnShort = NameEnShort;
    }

    public String getNameTc() {
        return NameTc;
    }

    public void setNameTc(String NameTc) {
        this.NameTc = NameTc;
    }

    public String getNameSc() {
        return NameSc;
    }

    public void setNameSc(String NameSc) {
        this.NameSc = NameSc;
    }

    public String getOrdering() {
        return Ordering;
    }

    public void setOrdering(String Ordering) {
        this.Ordering = Ordering;
    }

    // KEEP METHODS - put your custom methods here
    public void parser(String[] strings) {
        this.IndustryID = strings[0];
        this.NameEn = strings[1];
        this.NameEnShort = strings[2];
        this.NameTc = strings[3];
        this.NameSc = strings[4];
        this.Ordering = strings[5];
    }
    // KEEP METHODS END

}
