package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRODUCT_ID".
 */
public class ProductID {

    private String IndustryID;
    /** Not-null value. */
    private String IndustryIdParent;

    // KEEP FIELDS - put your custom fields here
    public void parser(String[] inputStream){
		this.IndustryID=inputStream[0];
		this.IndustryIdParent=inputStream[1];
	}
    // KEEP FIELDS END

    public ProductID() {
    }

    public ProductID(String IndustryID) {
        this.IndustryID = IndustryID;
    }

    public ProductID(String IndustryID, String IndustryIdParent) {
        this.IndustryID = IndustryID;
        this.IndustryIdParent = IndustryIdParent;
    }

    public String getIndustryID() {
        return IndustryID;
    }

    public void setIndustryID(String IndustryID) {
        this.IndustryID = IndustryID;
    }

    /** Not-null value. */
    public String getIndustryIdParent() {
        return IndustryIdParent;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIndustryIdParent(String IndustryIdParent) {
        this.IndustryIdParent = IndustryIdParent;
    }

    // KEEP METHODS - put your custom methods here
//    public String IndustryName;
    // KEEP METHODS END

}
