package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SCHEDULE_INFO".
 */
public class ScheduleInfo implements java.io.Serializable {

    private Long id;
    private String Title;
    private String Note;
    private String Location;
    private String CompanyID;
    private String StartTime;
    private Integer Length;
    private Integer Allday;
    private String Event_CId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ScheduleInfo() {
    }

    public ScheduleInfo(Long id) {
        this.id = id;
    }

    public ScheduleInfo(Long id, String Title, String Note, String Location, String CompanyID, String StartTime, Integer Length, Integer Allday,String event_CId) {
        this.id = id;
        this.Title = Title;
        this.Note = Note;
        this.Location = Location;
        this.CompanyID = CompanyID;
        this.StartTime = StartTime;
        this.Length = Length;
        this.Allday = Allday;
        this.Event_CId=event_CId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getNote() {
        return Note;
    }

    public void setNote(String Note) {
        this.Note = Note;
    }

    public String getLocation() {
        return Location;
    }

    public void setLocation(String Location) {
        this.Location = Location;
    }

    public String getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public String getStartTime() {
        return StartTime;
    }

    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    public Integer getLength() {
        return Length;
    }

    public void setLength(Integer Length) {
        this.Length = Length;
    }

    public Integer getAllday() {
        return Allday;
    }

    public void setAllday(Integer Allday) {
        this.Allday = Allday;
    }

    public String getEvent_CId() {
        return Event_CId;
    }

    public void setEvent_CId(String event_CId) {
        Event_CId = event_CId;
    }
    // KEEP METHODS - put your custom methods here
//    public String getStartTime(int curLanguage) {
//		return DateUtils.FormatDateByString("yyyy-MM-dd HH:mm",
//				"yyyy-MM-dd hh:mm a", StartTime);
//	}

    @Override
    public String toString() {
        return "ScheduleInfo{" +
                "id=" + id +
                ", Title='" + Title + '\'' +
                ", Note='" + Note + '\'' +
                ", Location='" + Location + '\'' +
                ", CompanyID='" + CompanyID + '\'' +
                ", StartTime='" + StartTime + '\'' +
                ", Length=" + Length +
                ", Allday=" + Allday +
                ", Event_CId='" + Event_CId + '\'' +
                '}';
    }


    // KEEP METHODS END

}
