package com.adsale.ChinaPlas.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

//2017.8.11
//把 LENGTH 当成 分钟；
//把 ALLDAY 当成 小时；

// KEEP INCLUDES END

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "SCHEDULE_INFO".
 */
public class ScheduleInfo implements Parcelable {

    private Long id;
    private String Title;
    private String Note;
    private String Location;
    private String CompanyID;


    private String Event_CId;

    // KEEP FIELDS - put your custom fields here
    private String StartDate = "2018-04-24";
    private String StartTime = "09:00";
    private Integer Hour=0;
    private Integer Minute=15;
    // KEEP FIELDS END

    public ScheduleInfo() {
    }

    public ScheduleInfo(Long id) {
        this.id = id;
    }

    public ScheduleInfo(Long id, String Title, String Note, String Location, String CompanyID,  String StartDate,String StartTime, Integer Hour, Integer Minute,String event_CId) {
        this.id = id;
        this.Title = Title;
        this.Note = Note;
        this.Location = Location;
        this.CompanyID = CompanyID;
        this.StartDate = StartDate;
        this.StartTime = StartTime;
        this.Hour = Hour;
        this.Minute = Minute;
        this.Event_CId=event_CId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getNote() {
        return Note;
    }

    public void setNote(String Note) {
        this.Note = Note;
    }

    public String getLocation() {
        return Location;
    }

    public void setLocation(String Location) {
        this.Location = Location;
    }

    public String getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public String getStartDate() {
        return StartDate;    }

    public void setStartDate(String StartDate) {
        this.StartDate = StartDate;
    }

    public String getStartTime() {
        return StartTime;    }

    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    public Integer getHour() {
        return Hour;
    }

    public Integer getMinute() {
        return Minute;
    }

    public void setHour(Integer hour) {
        Hour = hour;
    }

    public void setMinute(Integer minute) {
        Minute = minute;
    }

    public String getEvent_CId() {
        return Event_CId;
    }

    public void setEvent_CId(String event_CId) {
        Event_CId = event_CId;
    }
    // KEEP METHODS - put your custom methods here
//    public String getStartTime(int curLanguage) {
//		return DateUtils.FormatDateByString("yyyy-MM-dd HH:mm",
//				"yyyy-MM-dd hh:mm a", StartTime);
//	}

    @Override
    public String toString() {
        return "ScheduleInfo{" +
                "id=" + id +
                ", Title='" + Title + '\'' +
                ", Note='" + Note + '\'' +
                ", Location='" + Location + '\'' +
                ", CompanyID='" + CompanyID + '\'' +
                ", StartDate='" + StartDate + '\'' +
                ", StartTime='" + StartTime + '\'' +
                ", Hour=" + Hour +
                ", Minute=" + Minute +
                ", Event_CId='" + Event_CId + '\'' +
                '}';
    }


    // KEEP METHODS END

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.Title);
        dest.writeString(this.Note);
        dest.writeString(this.Location);
        dest.writeString(this.CompanyID);
        dest.writeString(this.StartDate);
        dest.writeString(this.StartTime);
        dest.writeValue(this.Hour);
        dest.writeValue(this.Minute);
        dest.writeString(this.Event_CId);
    }

    protected ScheduleInfo(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.Title = in.readString();
        this.Note = in.readString();
        this.Location = in.readString();
        this.CompanyID = in.readString();
        this.StartDate = in.readString();
        this.StartTime = in.readString();
        this.Hour = (Integer) in.readValue(Integer.class.getClassLoader());
        this.Minute = (Integer) in.readValue(Integer.class.getClassLoader());
        this.Event_CId = in.readString();
    }

    public static final Parcelable.Creator<ScheduleInfo> CREATOR = new Parcelable.Creator<ScheduleInfo>() {
        public ScheduleInfo createFromParcel(Parcel source) {
            return new ScheduleInfo(source);
        }

        public ScheduleInfo[] newArray(int size) {
            return new ScheduleInfo[size];
        }
    };
}
