package com.adsale.ChinaPlas.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.adsale.ChinaPlas.dao.UpdateCenter;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UPDATE_CENTER".
*/
public class UpdateCenterDao extends AbstractDao<UpdateCenter, Long> {

    public static final String TABLENAME = "UPDATE_CENTER";

    /**
     * Properties of entity UpdateCenter.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ScanFile = new Property(1, String.class, "ScanFile", false, "SCAN_FILE");
        public final static Property LUT = new Property(2, String.class, "LUT", false, "LUT");
        public final static Property Status = new Property(3, Integer.class, "Status", false, "STATUS");
    };


    public UpdateCenterDao(DaoConfig config) {
        super(config);
    }
    
    public UpdateCenterDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UPDATE_CENTER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SCAN_FILE\" TEXT," + // 1: ScanFile
                "\"LUT\" TEXT," + // 2: LUT
                "\"STATUS\" INTEGER);"); // 3: Status
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UPDATE_CENTER\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UpdateCenter entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ScanFile = entity.getScanFile();
        if (ScanFile != null) {
            stmt.bindString(2, ScanFile);
        }
 
        String LUT = entity.getLUT();
        if (LUT != null) {
            stmt.bindString(3, LUT);
        }
 
        Integer Status = entity.getStatus();
        if (Status != null) {
            stmt.bindLong(4, Status);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UpdateCenter readEntity(Cursor cursor, int offset) {
        UpdateCenter entity = new UpdateCenter( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ScanFile
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // LUT
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // Status
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UpdateCenter entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setScanFile(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLUT(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStatus(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UpdateCenter entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UpdateCenter entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
